# fly.toml app configuration file generated for logd on 2024-01-05T16:53:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# TODO
#  Configure swap
#
# SET SECRETS
#  LOGD_READ_SECRET
#  LOGD_WRITE_SECRET
#  LOGD_SLACK_WEBHOOK
#
#  fly secrets set LOGD_READ_SECRET=... LOGD_WRITE_SECRET=... LOGD_SLACK_WEBHOOK=...
#

app = "logd"
primary_region = "ams"

[build]
  dockerfile = "fly.Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  LOGD_UDP_LADDRPORT = "fly-global-services:6102"

[mounts]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 6101

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  protocol = "udp"
  internal_port = 6102

  [[services.ports]]
    port = 6102

[[vm]]
  memory = "2GB"
  cpus = 1
  cpu_kind = "shared"
